export enum AuthorizationType {
    NO_AUTHORIZATION = "NO_AUTHORIZATION",
    HTTP_BASIC_AUTHORIZATION = "HTTP_BASIC_AUTHORIZATION",
    HEADER_BASED_AUTHORIZATION = "HEADER_BASED_AUTHORIZATION",
    OAUTH_AUTHORIZATION = "OAUTH_AUTHORIZATION",
}
