export enum ErrorCodes {
    IdDoesNotExists = "MESSAGE.ID-DOES-NOT-EXIST",
    IdMissing = "MESSAGE.ID-MISSING-FROM-REQUEST",
    NameInvalidOrAlreadyInUse = "MESSAGE.NAME-INVALID-OR-ALREADY-IN-USE",
    InvalidApiKey = "MESSAGE.DEVICE-DOES-NOT-EXIST",
    InvalidPost = "MESSAGE.POST-FAILED",
    WrongLength = "MESSAGE.WRONG-LENGTH",
    NotValidFormat = "MESSAGE.NOT-VALID-FORMAT",
    BadEncoding = "MESSAGE.BAD-ENCODING",
    MissingOTAAInfo = "MESSAGE.OTAA-INFO-MISSING",
    MissingABPInfo = "MESSAGE.ABP-INFO-MISSING",
    UserAlreadyExists = "MESSAGE.USER-ALREADY-EXISTS",
    OrganizationAlreadyExists = "MESSAGE.ORGANIZATION-ALREADY-EXISTS",
    OrganizationDoesNotExists = "MESSAGE.ORGANIZATION-DOES-NOT-EXISTS",
    UserInactive = "MESSAGE.USER-INACTIVE",
    NotSameApplication = "MESSAGE.NOT-SAME-APPLICATION",
}
