import {MigrationInterface, QueryRunner} from "typeorm";

export class Initial1641894827503 implements MigrationInterface {
    name = 'Initial1641894827503'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "open_data_dk_dataset" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "keywords" text array, "license" character varying NOT NULL, "authorName" character varying NOT NULL, "authorEmail" character varying NOT NULL, "resourceTitle" character varying NOT NULL DEFAULT '', "createdById" integer, "updatedById" integer, "dataTargetId" integer, CONSTRAINT "REL_a0b7439e2a06cd0b67c4486a4f" UNIQUE ("dataTargetId"), CONSTRAINT "PK_07c9a82d4ee55c1207a2ce17731" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "received_message" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "rawData" jsonb NOT NULL, "sentTime" TIMESTAMP NOT NULL, "createdById" integer, "updatedById" integer, "deviceId" integer, CONSTRAINT "REL_b0a8014e917afd2b1152c83dc1" UNIQUE ("deviceId"), CONSTRAINT "PK_0bd1cfe05dbb3bc22d0abbcf7ac" PRIMARY KEY ("id")); COMMENT ON COLUMN "received_message"."sentTime" IS 'Time reported by device (if possible, otherwise time received)'`);
        await queryRunner.query(`CREATE TABLE "received_message_metadata" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "sentTime" TIMESTAMP NOT NULL, "signalData" jsonb, "createdById" integer, "updatedById" integer, "deviceId" integer, CONSTRAINT "PK_95d11e96204b0a42da220970411" PRIMARY KEY ("id")); COMMENT ON COLUMN "received_message_metadata"."sentTime" IS 'Time reported by device (if possible, otherwise time received)'`);
        await queryRunner.query(`CREATE INDEX "IDX_4e710f4b84fd89dbbbab4616bf" ON "received_message_metadata" ("deviceId", "sentTime") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "email" character varying, "passwordHash" character varying, "active" boolean NOT NULL DEFAULT true, "lastLogin" TIMESTAMP, "nameId" character varying, "createdById" integer, "updatedById" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "permission_type_enum" AS ENUM('GlobalAdmin', 'OrganizationAdmin', 'Write', 'Read', 'OrganizationPermission', 'OrganizationApplicationPermissions')`);
        await queryRunner.query(`CREATE TABLE "permission" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" "permission_type_enum" NOT NULL, "name" character varying NOT NULL, "automaticallyAddNewApplications" boolean DEFAULT false, "createdById" integer, "updatedById" integer, "organizationId" integer, CONSTRAINT "PK_3b8b97af9d9d8807e41e6f48362" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71bf2818fb2ad92e208d7aeadf" ON "permission" ("type") `);
        await queryRunner.query(`CREATE TABLE "payload_decoder" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "decodingFunction" text NOT NULL, "createdById" integer, "updatedById" integer, "organizationId" integer, CONSTRAINT "PK_04d515ff430849ef550db2f4495" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sigfox_group" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "username" character varying NOT NULL, "password" character varying NOT NULL, "sigfoxGroupId" character varying NOT NULL DEFAULT '', "createdById" integer, "updatedById" integer, "belongsToId" integer, CONSTRAINT "UQ_c658773871b8ec5ad9f9f4f692d" UNIQUE ("username", "belongsToId"), CONSTRAINT "PK_d4573623c283131a7901097798d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "createdById" integer, "updatedById" integer, CONSTRAINT "UQ_c21e615583a3ebbb0977452afb0" UNIQUE ("name"), CONSTRAINT "UQ_c21e615583a3ebbb0977452afb0" UNIQUE ("name"), CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "device_model" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "body" jsonb, "createdById" integer, "updatedById" integer, "belongsToId" integer, CONSTRAINT "PK_0ad50a03f4778f2d1dc83386a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "iot_device_type_enum" AS ENUM('GENERIC_HTTP', 'LORAWAN', 'SIGFOX')`);
        await queryRunner.query(`CREATE TABLE "iot_device" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "location" geometry(Point,4326), "commentOnLocation" character varying, "comment" character varying, "metadata" jsonb, "type" "iot_device_type_enum" NOT NULL, "apiKey" character varying, "deviceEUI" character varying, "chirpstackApplicationId" integer, "deviceId" character varying, "deviceTypeId" character varying, "groupId" character varying, "downlinkPayload" character varying, "createdById" integer, "updatedById" integer, "applicationId" integer, "deviceModelId" integer, CONSTRAINT "PK_9ebe9e6bfa9a631bfba27b3d57d" PRIMARY KEY ("id")); COMMENT ON COLUMN "iot_device"."apiKey" IS 'Used for GenericHTTPDevice'`);
        await queryRunner.query(`CREATE INDEX "IDX_18ce5007f4efcbe92338c10f5d" ON "iot_device" ("type") `);
        await queryRunner.query(`CREATE TABLE "iot_device_payload_decoder_data_target_connection" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdById" integer, "updatedById" integer, "payloadDecoderId" integer, "dataTargetId" integer, CONSTRAINT "PK_a0470515beb1c8087c4e868bf06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7055bf87cc824d4d1268704818" ON "iot_device_payload_decoder_data_target_connection" ("dataTargetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ef58c35ae5562242966d483a1" ON "iot_device_payload_decoder_data_target_connection" ("payloadDecoderId") `);
        await queryRunner.query(`CREATE TYPE "data_target_type_enum" AS ENUM('HTTP_PUSH')`);
        await queryRunner.query(`CREATE TABLE "data_target" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" "data_target_type_enum" NOT NULL, "name" character varying NOT NULL, "url" character varying, "timeout" integer DEFAULT '30000', "authorizationHeader" character varying, "createdById" integer, "updatedById" integer, "applicationId" integer, CONSTRAINT "PK_cd4e902e1acce0793eeba6d0dc5" PRIMARY KEY ("id")); COMMENT ON COLUMN "data_target"."timeout" IS 'HTTP call timeout in milliseconds'`);
        await queryRunner.query(`CREATE INDEX "IDX_af951594386c64a22f8fc057be" ON "data_target" ("type") `);
        await queryRunner.query(`CREATE TABLE "application" ("id" SERIAL NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "description" character varying, "createdById" integer, "updatedById" integer, "belongsToId" integer, CONSTRAINT "UQ_608bb41e7e1ef5f6d7abb07e394" UNIQUE ("name"), CONSTRAINT "PK_569e0c3e863ebdf5f2408ee1670" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_permissions_permission" ("userId" integer NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "PK_8dd49853fbad35f9a0f91b11877" PRIMARY KEY ("userId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5b72d197d92b8bafbe7906782e" ON "user_permissions_permission" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c43a6a56e3ef281cbfba9a7745" ON "user_permissions_permission" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev" ("iotDevicePayloadDecoderDataTargetConnectionId" integer NOT NULL, "iotDeviceId" integer NOT NULL, CONSTRAINT "PK_f03f957266ca9997d3f492ed018" PRIMARY KEY ("iotDevicePayloadDecoderDataTargetConnectionId", "iotDeviceId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_daf134b834f403ea98efa1fc09" ON "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev" ("iotDevicePayloadDecoderDataTargetConnectionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c88fdc6da057254fe8f9e15555" ON "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev" ("iotDeviceId") `);
        await queryRunner.query(`CREATE TABLE "application_permissions_permission" ("applicationId" integer NOT NULL, "permissionId" integer NOT NULL, CONSTRAINT "PK_27688b5488c8a5b7fc415663a17" PRIMARY KEY ("applicationId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6c691b1ba972915dc7bf324420" ON "application_permissions_permission" ("applicationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1bbb34687ca84f2a166ee376e" ON "application_permissions_permission" ("permissionId") `);
        await queryRunner.query(`ALTER TABLE "open_data_dk_dataset" ADD CONSTRAINT "FK_981af5bddacc8b7bf9f37247fb6" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "open_data_dk_dataset" ADD CONSTRAINT "FK_d5b350d2e5efe0229d8e01f7507" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "open_data_dk_dataset" ADD CONSTRAINT "FK_a0b7439e2a06cd0b67c4486a4f7" FOREIGN KEY ("dataTargetId") REFERENCES "data_target"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "received_message" ADD CONSTRAINT "FK_38b28c3a0241fcec40207e0745d" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "received_message" ADD CONSTRAINT "FK_21ec54fded11c9d4ee8df3c17dd" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "received_message" ADD CONSTRAINT "FK_b0a8014e917afd2b1152c83dc10" FOREIGN KEY ("deviceId") REFERENCES "iot_device"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "received_message_metadata" ADD CONSTRAINT "FK_4834b1a60043b2c443b07c08b17" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "received_message_metadata" ADD CONSTRAINT "FK_8399e14dc77145a32ccb755a84d" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "received_message_metadata" ADD CONSTRAINT "FK_de1719d0660b369de300440ad6f" FOREIGN KEY ("deviceId") REFERENCES "iot_device"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_45c0d39d1f9ceeb56942db93cc5" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_db5173f7d27aa8a98a9fe6113df" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permission" ADD CONSTRAINT "FK_00e2c09abd157b5358faf3f43d0" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permission" ADD CONSTRAINT "FK_40c4877af6e402a449d56af4d39" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permission" ADD CONSTRAINT "FK_2102b10c8a5424189ac612ca8d9" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payload_decoder" ADD CONSTRAINT "FK_33f98e074272079c02d792aa852" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payload_decoder" ADD CONSTRAINT "FK_ce6313b2fa3de41f2d4d9409003" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payload_decoder" ADD CONSTRAINT "FK_20c47c4f5719e0d398743401acd" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sigfox_group" ADD CONSTRAINT "FK_f5401745b31e0eedff2d219f77d" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sigfox_group" ADD CONSTRAINT "FK_23d9047d051ab1ad8875306ae98" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sigfox_group" ADD CONSTRAINT "FK_a38129f018eb963aea886de12e9" FOREIGN KEY ("belongsToId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_acdbd1e490930af04b4ff569ca9" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_a7a6b96e8460aeb314599cf3580" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_model" ADD CONSTRAINT "FK_9d26f066b617bbdac41d72e82b2" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_model" ADD CONSTRAINT "FK_ed6727d1c4a7f9e6299ba6e2961" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "device_model" ADD CONSTRAINT "FK_75a9d1c5495facf583614ca2b5f" FOREIGN KEY ("belongsToId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device" ADD CONSTRAINT "FK_36879bbabdd338403df3639ebf7" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device" ADD CONSTRAINT "FK_a15ceb5dd1d6c1eff4bccddc513" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device" ADD CONSTRAINT "FK_3e4f8964a797bd27b29a72a4718" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device" ADD CONSTRAINT "FK_bd1fee6c283fe1db22aeed6ac36" FOREIGN KEY ("deviceModelId") REFERENCES "device_model"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" ADD CONSTRAINT "FK_e1e5066f7ec7093fe51b9a84eca" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" ADD CONSTRAINT "FK_dfe8b280f6a586177f7f2badc2f" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" ADD CONSTRAINT "FK_1ef58c35ae5562242966d483a16" FOREIGN KEY ("payloadDecoderId") REFERENCES "payload_decoder"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" ADD CONSTRAINT "FK_7055bf87cc824d4d1268704818b" FOREIGN KEY ("dataTargetId") REFERENCES "data_target"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_target" ADD CONSTRAINT "FK_062e2d7b403e1d9736d3a26c86e" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_target" ADD CONSTRAINT "FK_aec53ab5541644651b38921719d" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "data_target" ADD CONSTRAINT "FK_dc5681eea8037a19634c4630057" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_d7021375eb0ef5d648641b78886" FOREIGN KEY ("createdById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_faa0fa6bed13e319c54ad6c4636" FOREIGN KEY ("updatedById") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "FK_7eb7ebc6eb5a830b9fb78030a8e" FOREIGN KEY ("belongsToId") REFERENCES "organization"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions_permission" ADD CONSTRAINT "FK_5b72d197d92b8bafbe7906782ec" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_permissions_permission" ADD CONSTRAINT "FK_c43a6a56e3ef281cbfba9a77457" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev" ADD CONSTRAINT "FK_daf134b834f403ea98efa1fc09f" FOREIGN KEY ("iotDevicePayloadDecoderDataTargetConnectionId") REFERENCES "iot_device_payload_decoder_data_target_connection"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev" ADD CONSTRAINT "FK_c88fdc6da057254fe8f9e155559" FOREIGN KEY ("iotDeviceId") REFERENCES "iot_device"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_permissions_permission" ADD CONSTRAINT "FK_6c691b1ba972915dc7bf3244204" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_permissions_permission" ADD CONSTRAINT "FK_c1bbb34687ca84f2a166ee376e2" FOREIGN KEY ("permissionId") REFERENCES "permission"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "application_permissions_permission" DROP CONSTRAINT "FK_c1bbb34687ca84f2a166ee376e2"`);
        await queryRunner.query(`ALTER TABLE "application_permissions_permission" DROP CONSTRAINT "FK_6c691b1ba972915dc7bf3244204"`);
        await queryRunner.query(`ALTER TABLE "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev" DROP CONSTRAINT "FK_c88fdc6da057254fe8f9e155559"`);
        await queryRunner.query(`ALTER TABLE "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev" DROP CONSTRAINT "FK_daf134b834f403ea98efa1fc09f"`);
        await queryRunner.query(`ALTER TABLE "user_permissions_permission" DROP CONSTRAINT "FK_c43a6a56e3ef281cbfba9a77457"`);
        await queryRunner.query(`ALTER TABLE "user_permissions_permission" DROP CONSTRAINT "FK_5b72d197d92b8bafbe7906782ec"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_7eb7ebc6eb5a830b9fb78030a8e"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_faa0fa6bed13e319c54ad6c4636"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "FK_d7021375eb0ef5d648641b78886"`);
        await queryRunner.query(`ALTER TABLE "data_target" DROP CONSTRAINT "FK_dc5681eea8037a19634c4630057"`);
        await queryRunner.query(`ALTER TABLE "data_target" DROP CONSTRAINT "FK_aec53ab5541644651b38921719d"`);
        await queryRunner.query(`ALTER TABLE "data_target" DROP CONSTRAINT "FK_062e2d7b403e1d9736d3a26c86e"`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" DROP CONSTRAINT "FK_7055bf87cc824d4d1268704818b"`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" DROP CONSTRAINT "FK_1ef58c35ae5562242966d483a16"`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" DROP CONSTRAINT "FK_dfe8b280f6a586177f7f2badc2f"`);
        await queryRunner.query(`ALTER TABLE "iot_device_payload_decoder_data_target_connection" DROP CONSTRAINT "FK_e1e5066f7ec7093fe51b9a84eca"`);
        await queryRunner.query(`ALTER TABLE "iot_device" DROP CONSTRAINT "FK_bd1fee6c283fe1db22aeed6ac36"`);
        await queryRunner.query(`ALTER TABLE "iot_device" DROP CONSTRAINT "FK_3e4f8964a797bd27b29a72a4718"`);
        await queryRunner.query(`ALTER TABLE "iot_device" DROP CONSTRAINT "FK_a15ceb5dd1d6c1eff4bccddc513"`);
        await queryRunner.query(`ALTER TABLE "iot_device" DROP CONSTRAINT "FK_36879bbabdd338403df3639ebf7"`);
        await queryRunner.query(`ALTER TABLE "device_model" DROP CONSTRAINT "FK_75a9d1c5495facf583614ca2b5f"`);
        await queryRunner.query(`ALTER TABLE "device_model" DROP CONSTRAINT "FK_ed6727d1c4a7f9e6299ba6e2961"`);
        await queryRunner.query(`ALTER TABLE "device_model" DROP CONSTRAINT "FK_9d26f066b617bbdac41d72e82b2"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_a7a6b96e8460aeb314599cf3580"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_acdbd1e490930af04b4ff569ca9"`);
        await queryRunner.query(`ALTER TABLE "sigfox_group" DROP CONSTRAINT "FK_a38129f018eb963aea886de12e9"`);
        await queryRunner.query(`ALTER TABLE "sigfox_group" DROP CONSTRAINT "FK_23d9047d051ab1ad8875306ae98"`);
        await queryRunner.query(`ALTER TABLE "sigfox_group" DROP CONSTRAINT "FK_f5401745b31e0eedff2d219f77d"`);
        await queryRunner.query(`ALTER TABLE "payload_decoder" DROP CONSTRAINT "FK_20c47c4f5719e0d398743401acd"`);
        await queryRunner.query(`ALTER TABLE "payload_decoder" DROP CONSTRAINT "FK_ce6313b2fa3de41f2d4d9409003"`);
        await queryRunner.query(`ALTER TABLE "payload_decoder" DROP CONSTRAINT "FK_33f98e074272079c02d792aa852"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP CONSTRAINT "FK_2102b10c8a5424189ac612ca8d9"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP CONSTRAINT "FK_40c4877af6e402a449d56af4d39"`);
        await queryRunner.query(`ALTER TABLE "permission" DROP CONSTRAINT "FK_00e2c09abd157b5358faf3f43d0"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_db5173f7d27aa8a98a9fe6113df"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_45c0d39d1f9ceeb56942db93cc5"`);
        await queryRunner.query(`ALTER TABLE "received_message_metadata" DROP CONSTRAINT "FK_de1719d0660b369de300440ad6f"`);
        await queryRunner.query(`ALTER TABLE "received_message_metadata" DROP CONSTRAINT "FK_8399e14dc77145a32ccb755a84d"`);
        await queryRunner.query(`ALTER TABLE "received_message_metadata" DROP CONSTRAINT "FK_4834b1a60043b2c443b07c08b17"`);
        await queryRunner.query(`ALTER TABLE "received_message" DROP CONSTRAINT "FK_b0a8014e917afd2b1152c83dc10"`);
        await queryRunner.query(`ALTER TABLE "received_message" DROP CONSTRAINT "FK_21ec54fded11c9d4ee8df3c17dd"`);
        await queryRunner.query(`ALTER TABLE "received_message" DROP CONSTRAINT "FK_38b28c3a0241fcec40207e0745d"`);
        await queryRunner.query(`ALTER TABLE "open_data_dk_dataset" DROP CONSTRAINT "FK_a0b7439e2a06cd0b67c4486a4f7"`);
        await queryRunner.query(`ALTER TABLE "open_data_dk_dataset" DROP CONSTRAINT "FK_d5b350d2e5efe0229d8e01f7507"`);
        await queryRunner.query(`ALTER TABLE "open_data_dk_dataset" DROP CONSTRAINT "FK_981af5bddacc8b7bf9f37247fb6"`);
        await queryRunner.query(`DROP INDEX "IDX_c1bbb34687ca84f2a166ee376e"`);
        await queryRunner.query(`DROP INDEX "IDX_6c691b1ba972915dc7bf324420"`);
        await queryRunner.query(`DROP TABLE "application_permissions_permission"`);
        await queryRunner.query(`DROP INDEX "IDX_c88fdc6da057254fe8f9e15555"`);
        await queryRunner.query(`DROP INDEX "IDX_daf134b834f403ea98efa1fc09"`);
        await queryRunner.query(`DROP TABLE "iot_dev_pay_dec_dat_tar_con_iot_dev_iot_dev"`);
        await queryRunner.query(`DROP INDEX "IDX_d38b5d829712b4e0df2bae160f"`);
        await queryRunner.query(`DROP INDEX "IDX_9b91f8a9dcc02c5926fced99e1"`);
        await queryRunner.query(`DROP INDEX "IDX_0c5a137689ddc88c8257e2cd46"`);
        await queryRunner.query(`DROP INDEX "IDX_f502bc0bd3c1406ae2b3dc1562"`);
        await queryRunner.query(`DROP INDEX "IDX_c43a6a56e3ef281cbfba9a7745"`);
        await queryRunner.query(`DROP INDEX "IDX_5b72d197d92b8bafbe7906782e"`);
        await queryRunner.query(`DROP TABLE "user_permissions_permission"`);
        await queryRunner.query(`DROP TABLE "application"`);
        await queryRunner.query(`DROP INDEX "IDX_af951594386c64a22f8fc057be"`);
        await queryRunner.query(`DROP TABLE "data_target"`);
        await queryRunner.query(`DROP TYPE "data_target_type_enum"`);
        await queryRunner.query(`DROP INDEX "IDX_1ef58c35ae5562242966d483a1"`);
        await queryRunner.query(`DROP INDEX "IDX_7055bf87cc824d4d1268704818"`);
        await queryRunner.query(`DROP TABLE "iot_device_payload_decoder_data_target_connection"`);
        await queryRunner.query(`DROP INDEX "IDX_18ce5007f4efcbe92338c10f5d"`);
        await queryRunner.query(`DROP TABLE "iot_device"`);
        await queryRunner.query(`DROP TYPE "iot_device_type_enum"`);
        await queryRunner.query(`DROP TABLE "device_model"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TABLE "sigfox_group"`);
        await queryRunner.query(`DROP TABLE "payload_decoder"`);
        await queryRunner.query(`DROP INDEX "IDX_71bf2818fb2ad92e208d7aeadf"`);
        await queryRunner.query(`DROP TABLE "permission"`);
        await queryRunner.query(`DROP TYPE "permission_type_enum"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "IDX_4e710f4b84fd89dbbbab4616bf"`);
        await queryRunner.query(`DROP TABLE "received_message_metadata"`);
        await queryRunner.query(`DROP TABLE "received_message"`);
        await queryRunner.query(`DROP TABLE "open_data_dk_dataset"`);
    }

}
