name: GitHub Actions
on:
  push:
    branches:
      - "feature/github-actions" # DEBUGGING. REMOVE BEFORE MERGE
      - "stage"
      - "master"
    # paths:
    #   - "src/**" # DEBUGGING. ENABLE BEFORE MERGE
jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: debricked/actions/scan@v1
        env:
          USERNAME: ${{ secrets.DEBRICKED_USERNAME }}
          PASSWORD: ${{ secrets.DEBRICKED_PASSWORD }}
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: "Install packages"
        run: "npm ci"
      - name: "Build source"
        run: "npm run build"
