name: "[Production] OS2iot OnPush"
on:
  push:
    branches:
      - "stage"
      - "master"
    paths:
      - "src/**" # DEBUGGING. ENABLE BEFORE MERGE
jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: debricked/actions/scan@v1
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
  code-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: "Install packages"
        run: "npm ci"
      - name: "Build source"
        run: "npm run build"
